DROP TABLE ACCOUNT_USER IF EXISTS;

CREATE TABLE ACCOUNT_USER
(
    ID        INTEGER IDENTITY PRIMARY KEY,
    USER_ID BIGINT,
    USER_NAME  VARCHAR(200),
    VERSION    BIGINT,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    AMOUNT     DECIMAL
);

-- CREATE TABLE CUSTOMER_CREDIT_RESERVATIONS
-- (
--     CREDIT_RESERVATIONS_KEY BIGINT NOT NULL,
--     CUSTOMER_ID BIGINT NOT NULL,
--     AMOUNT DECIMAL,
--     PRIMARY KEY (CREDIT_RESERVATIONS_KEY, CUSTOMER_ID)
-- );
-- CREATE TABLE ACCOUNT_CREDIT
-- (
--     ID        INTEGER IDENTITY PRIMARY KEY,
--     AMOUNT     DECIMAL
-- );

CREATE TABLE CREDIT_RESERVATION (
        ID BIGINT IDENTITY PRIMARY KEY,
        CUSTOMER_ID BIGINT,
        ORDER_ID BIGINT,
        RESERVATION DECIMAL
);