database: @database.type@
server:
  port: 8080
spring:
  profiles:
    active: @spring.profiles.active@
  sql:
    init:
      schema-locations: classpath*:db/${database}/schema.sql
      data-locations: classpath*:db/${database}/data.sql
      platform: ${database}
      continue-on-error: false # 如果脚本执行出现异常是否继续执行后续脚本，默认false
      encoding: UTF-8
      mode: always
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  application:
    name: authServer
  web:
    resources:
      chain:
        compressed: true
        cache: true
      cache:
        period: 86400
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(-){faint} %clr([%t]){faint} %clr(%-40logger{39}){cyan}[%line]%clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
      hibernate: INFO
  file:
    path: tmp/logs