DROP TABLE AUTH_USER IF EXISTS;

CREATE TABLE AUTH_USER
(
    ID        INTEGER IDENTITY PRIMARY KEY,
    USERNAME  VARCHAR(50),
    PASSWORD  VARCHAR(100),
    ROLE    VARCHAR(100),
    TELEPHONE VARCHAR(20),
    EMAIL     VARCHAR(100),
    LOCATION VARCHAR(255)
);
CREATE UNIQUE INDEX USER_NAME_IDX ON AUTH_USER (USERNAME);

DROP TABLE AUTH_TOKEN IF EXISTS;
CREATE TABLE AUTH_TOKEN
(
    ID        INTEGER IDENTITY PRIMARY KEY,
    EXPIRED     BOOLEAN,
    REVOKED  BOOLEAN,
    USER_ID VARCHAR(100),
    TOKEN_STR    LONGVARCHAR ,
    TOKEN_TYPE VARCHAR(20),
);

