apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga-servicemesh-frontend
  namespace: saga-servicemesh
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: saga-admin
      containers:
        - name: gateway
          image: xiongzhenggang/saga-istio-frontend
          ports:
            - name: http-server
              containerPort: 80
          volumeMounts:
            - name: frontend-config
              mountPath: config
          env:
            - name: PORT
              value: "80"
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
      volumes:
        - name: frontend-config
          configMap:
            name: frontend
            items:
              - key: application.yaml
                path: application.yaml
