apiVersion: v1
kind: Service
metadata:
  name: goods
  namespace: saga-servicemesh
  labels:
    app: goods
spec:
  type: ClusterIP
  selector:
    app: goods
  ports:
  - port: 80
    name: http-server
    targetPort: http-server
