apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: saga-servicemesh
  labels:
    app: order
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
  - port: 80
    name: http-server
    targetPort: http-server
