apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: saga-admin-role-binding
  namespace: saga-servicemesh
roleRef:
  kind: Role
  name: saga-admin-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: saga-admin
    namespace: saga-servicemesh
