apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
  namespace: ${kube.namespace}
  labels:
    app: ${project.artifactId}
    team: xzg
spec:
  type: NodePort
  selector:
    app: ${project.artifactId}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30001

