appVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${project.artifactId}
  labels:
    app: ${project.artifactId}
    team: xzg
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${project.artifactId}
                port:
                  number: 80