DROP TABLE SAGA_INSTANCE IF EXISTS;
CREATE TABLE  SAGA_INSTANCE(
        ID VARCHAR(255)  NOT NULL,
        SAGA_TYPE VARCHAR(255) NOT NULL,
        STATE_NAME VARCHAR(255) NOT NULL,
        LAST_REQUEST_ID VARCHAR(100),
        END_STATE TINYINT,
        COMPENSATING TINYINT,
        FAILED TINYINT,
        SAGA_DATA_TYPE VARCHAR(255) NOT NULL,
        SAGA_DATA_JSON VARCHAR(255) NOT NULL,
        PRIMARY KEY (ID)
);
DROP TABLE DESTINATION_RESOURCE IF EXISTS;
CREATE TABLE  DESTINATION_RESOURCE(
        ID BIGINT NOT NULL,
        SAGA_ID VARCHAR(255) NOT NULL,
        DESTINATION  VARCHAR(255) ,
        RESOURCE VARCHAR(255),
        PRIMARY KEY (ID)
);

-- CREATE TABLE IF NOT EXISTS AGGREGATE_INSTANCE_SUBSCRIPTIONS(
--      AGGREGATE_TYPE VARCHAR(255) DEFAULT NULL,
--      AGGREGATE_ID VARCHAR(255) NOT NULL,
--      EVENT_TYPE VARCHAR(200) NOT NULL,
--      SAGA_ID VARCHAR(1000) NOT NULL,
--      SAGA_TYPE VARCHAR(200) NOT NULL,
--      PRIMARY KEY(AGGREGATE_ID, EVENT_TYPE, SAGA_ID, SAGA_TYPE)
-- );
--
-- CREATE TABLE IF NOT EXISTS SAGA_INSTANCE_PARTICIPANTS (
--     SAGA_TYPE VARCHAR(100) NOT NULL,
--     SAGA_ID VARCHAR(100) NOT NULL,
--     DESTINATION VARCHAR(100) NOT NULL,
--     RESOURCE VARCHAR(100) NOT NULL,
--     PRIMARY KEY(SAGA_TYPE, SAGA_ID, DESTINATION, RESOURCE)
-- );



