DROP TABLE GOODS_INFO IF EXISTS;

CREATE TABLE GOODS_INFO
(
    id        INTEGER IDENTITY PRIMARY KEY,
    goods_name  VARCHAR(200),
    STOCK  INTEGER,
    DESC  VARCHAR(200),
    URL  VARCHAR(200),
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255),
    create_time timestamp,
    update_time timestamp
);
