DROP TABLE GOODS_INFO IF EXISTS;

CREATE TABLE GOODS_INFO
(
    ID        INTEGER IDENTITY PRIMARY KEY,
    GOODS_NAME  VARCHAR(200),
    UNIT_PRICE DECIMAL,
    STOCK  INTEGER,
    DESC  VARCHAR(200),
    URL  VARCHAR(200),
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP
);
DROP TABLE IF EXISTS SAGA_MESSAGE;
CREATE TABLE SAGA_MESSAGE(
                             ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL  , --主键
                             SERIAL VARCHAR(255) NOT NULL  , --消息事件流水号：同一消息幂等
                             SAGA_ID VARCHAR(255) NOT NULL  ,
                             PAYLOAD VARCHAR(2048)  , --事件内容
                             TYPE VARCHAR(255)   , --事件消息类型
                             SEND_STATUS VARCHAR(255)   , --事件发送状态，发送中，已完成
                             SOURCE VARCHAR(32)   , --事件来源
                             HEADERS VARCHAR(2048)     , --消息头
                             UPDATED_TIME TIMESTAMP   , --更新时间
                             UPDATED_BY VARCHAR(255)   , --更新人
                             CREATED_TIME TIMESTAMP   , --创建时间
                             CREATED_BY VARCHAR(255)   , --创建人
                             PRIMARY KEY (ID)
)  ;