DROP TABLE GOODS_INFO IF EXISTS;

CREATE TABLE GOODS_INFO
(
    ID        INTEGER IDENTITY PRIMARY KEY,
    GOODS_NAME  VARCHAR(200),
    STOCK  INTEGER,
    DESC  VARCHAR(200),
    URL  VARCHAR(200),
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP
);
