database: hsqldb
server:
  port: 8081
spring:
  datasource:
    schema: "classpath:db/${database}/schema.sql"
    data: "classpath:db/${database}/data.sql"
    sql-script-encoding: UTF-8
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "order_account"
#    producer:
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  resources:
    chain:
      compressed: true
      cache: true
    cache:
      period: 86400
  application:
    name: account_server
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(-){faint} %clr([%t]){faint} %clr(%-40logger{39}){cyan}[%line]%clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: INFO
    org:
      springframework:
        security: INFO
      hibernate: INFO
saga:
    topic:
      name: customerServer
#  file:
#    path: tmp/logs